### ISSUE TITLE
incorrect value for --removed-body-scroll-bar-size calculation which causes page to shift when page zoom not 100%

### ISSUE THREAD

**Issue by Lexachoc** [theKashey/react-remove-scroll-bar#64]
Hi, I noticed that [Select – Radix Primitives](https://www.radix-ui.com/primitives/docs/components/select) will slightly shift the whole page when using page zoom other than 100% in Chrome, and then I found that this is due to the incorrect calculation of the value: `--removed-body-scroll-bar-size`!

https://github.com/theKashey/react-remove-scroll-bar/blob/e77dbb6614a03e0626fd823ded327dcbab9e12be/src/constants.ts#L8

For example, for Chrome, the value for `--removed-body-scroll-bar-size` is 16px (when having page zoom=110%).

and in Radix, it has below style when select is open (Chrome):
```css
body[data-scroll-locked] {
    overflow: hidden !important;
    overscroll-behavior: contain;
    position: relative !important;
    padding-left: 0px;
    padding-top: 0px;
    padding-right: 0px;
    margin-left: 0;
    margin-top: 0;
    margin-right: 16px !important;
}
```
(For default page zoom 100%, margin-right: 17px !important;)

but in fact, the value for `margin-right` should be around 15.5px (Page zoom also affects the value! I use 110%) in my case! Otherwise the page will shift.

Recording:
![recording](https://github.com/user-attachments/assets/a0ebde05-33d6-46c2-a2fa-37fcffe48711)

using 15.5px for Chrome (Page zoom also affects the value!):

```css
/*my fix*/
  html body[data-scroll-locked] {
    --removed-body-scroll-bar-size: 15.5 !important;
    margin-right: 15.5px !important;
  }
```
![recording](https://github.com/user-attachments/assets/31333dd6-dad2-4b2e-ba43-c898a9d3cf93)

Since the page zoom function also affects the value, I can't simply adjust the shift caused here with CSS.
